name: Generate Container Yaml
on:
  pull_request: []
  workflow_dispatch: 
    inputs:
      docker_uri:
        description: 'Docker identifier to generate recipe for'
        required: true
        default: "quay.io/autamus/clingo:5.5.1"

jobs:
  generate-recipe:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    name: ${{ inputs.docker_uri }}
    steps:
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate sbom
        docker_uri: ${{ inputs.docker_uri }}
        run: |
          if [ "${docker_uri}" == "" ]; then
              docker_uri=quay.io/autamus/clingo:5.5.1
          fi
          echo "Preparing ${docker_uri}"
          syft ${{ inputs.docker_uri }}
